@startuml
'https://plantuml.com/class-diagram

title: The dependencies between Keepers (Feb 2021)

abstract class Staking
abstract class Distribution
abstract class Slashing
abstract class Evidence
abstract class Bank
abstract class "Auth/Account" as Auth
abstract class Gov
abstract class Mint

Staking <|-- Mint
Bank <|-- Mint

Staking <|-- Gov
Bank <|-- Gov
Auth <|-- Gov

Auth <|-- Bank

Bank <|-- Distribution
Auth <|-- Distribution
Staking <|-- Distribution

Staking <|-- Evidence
Slashing <|-- Evidence

Staking <|-- Slashing

Auth <|-- Staking
Bank <|-- Staking

@enduml
