stateDiagram-v2
    [*] --> ComputeRunPlan
    state ComputeRunPlan {
        ReadUpgradeInfo --> ReadManualUpgradesBatch
        ReadUpgradeInfo --> DoUpgrade: have upgrade-info.json
        ReadManualUpgradesBatch --> Run: no manual upgrades
        ReadManualUpgradesBatch --> RunWithHaltHeight: have manual-upgrades-batch.json
        ReadLastKnownHeight
    }

    state DoUpgrade {
        CheckSkipUpgradeHeight --> DoBackup
        DoBackup --> CustomPreUpgrade
        CustomPreUpgrade --> SwitchToNewBinary
        SwitchToNewBinary --> RunPreUpgrade
        RunPreUpgrade
    }

    DoUpgrade --> ComputeRunPlan

%%    state Run {
%%    }
%%
%%    state RunWithHaltHeight {
%%    }