stateDiagram-v2
    [*] --> Init
    Init --> WaitForXUpgrade: no upgrade-info.json.batch
    Init --> ??: have upgrade-info.json
    Init --> StartWithHaltHeight: have upgrade-info.json.batch
    WaitForXUpgrade --> KillProcessAndUpgrade: got upgrade-info.json
    WaitForXUpgrade --> KillProcessAndAddHaltHeight: got upgrade-info.json.batch
    WaitForXUpgrade --> CheckForUpgradeInfo: process exited
    CheckForUpgradeInfo --> ShutdownAndError: no upgrade-info.json
    StartWithHaltHeight --> WaitForManualUpgrade
    WaitForManualUpgrade --> KillProcessAndUpgrade: got upgrade-info.json
    WaitForManualUpgrade --> KillProcessAndAddHaltHeight: got upgrade-info.json.batch
    WaitForManualUpgrade --> KillProcessAndUpgrade: height == halt-height
    WaitForManualUpgrade --> ShutdownAndError: height > halt-height
    WaitForManualUpgrade --> CheckForManualUpgrade: process exited
    CheckForManualUpgrade --> ShutdownAndError: can't confirm upgrade
    CheckForManualUpgrade --> DoUpgrade: confirmed halt-height or upgrade-info.json
    KillProcessAndAddHaltHeight --> StartWithHaltHeight: process existed
    KillProcessAndUpgrade --> DoUpgrade: process exited
    DoUpgrade --> CheckSkipUpgradeHeight
    CheckSkipUpgradeHeight --> DoBackup
    CheckSkipUpgradeHeight --> Init: skip upgrade
    DoBackup --> CustomPreUpgrade
    CustomPreUpgrade --> SwitchToNewBinary
    SwitchToNewBinary --> RunPreUpgrade
    RunPreUpgrade --> Init: have new binary
    RunPreUpgrade --> ShutdownAndError: no new binary
    RunPreUpgrade --> GracefulShutdown: daemon restart disabled
