version: "2"
run:
  tests: true
  timeout: 15m
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dogsled
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 6
    gocritic:
      disabled-checks:
        - regexpMust
        - appendAssign
        - ifElseChain
        - deprecatedComment
    gosec:
      includes:
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G111
        - G112
        - G113
        - G114
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
        - G601
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1016:'
      - linters:
          - staticcheck
        path: migrations
        text: 'SA1019:'
      - linters:
          - staticcheck
        text: 'SA1019: codec.NewAminoCodec is deprecated'
      - linters:
          - nolintlint
        text: leading space
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: var-naming
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - staticcheck
        text: 'SA1029:'
      - linters:
          - staticcheck
        text: 'SA1032:'
      - linters:
          - staticcheck
        text: 'S1009:'
      - linters:
          - staticcheck
        text: 'ST1008:'
      - linters:
          - gosec
        text: 'G601:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
      custom-order: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
