FROM golang:latest

RUN apt-get update && apt-get install -y jq

RUN mkdir -p /go/src/github.com/cosmos/cosmos-sdk
WORKDIR /go/src/github.com/cosmos/cosmos-sdk

COPY Makefile /go/src/github.com/cosmos/cosmos-sdk/
COPY glide.yaml /go/src/github.com/cosmos/cosmos-sdk/
COPY glide.lock /go/src/github.com/cosmos/cosmos-sdk/

RUN make get_vendor_deps

COPY . /go/src/github.com/cosmos/cosmos-sdk
