#!/bin/bash

set -e

CMDS='git go gofmt goimports misspell'
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

f_echo_stderr() {
  echo "$@" >&2
}

f_exit_success() {
  if [[ -n "$*" ]]; then
    f_echo_stderr "$*"
  fi
  exit 0
}
trap f_exit_success EXIT

f_check_cmds() {
  for cmd in $CMDS; do
    if ! command -v "$cmd" &>/dev/null; then
      f_exit_success "Couldn't find '$cmd', skipping"
    fi
  done
}

f_check_cmds

if [[ -n "$STAGED_GO_FILES" ]]; then
  f_echo_stderr "[pre-commit] Formatting staged files..."
  for file in $STAGED_GO_FILES; do
    if [[ "$file" =~ vendor/ ]] || [[ "$file" =~ tests/mocks/ ]] || [[ "$file" =~ \.pb\.go$ ]]; then
      continue
    fi

    gofmt -w -s "$file"
    misspell -w "$file"
    goimports -w -local github.com/cosmos/cosmos-sdk "$file"
    git add "$file"
  done
fi

# Run go mod tidy
go mod tidy && git add go.mod go.sum
