#!/bin/bash

set -e

CMDS='gofmt goimports misspell'
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

f_exit_success_with_msg() {
  echo $@ >&2
  exit 0
}

f_check_cmds() {
  for cmd in ${CMDS}; do
    which ${cmd} &>/dev/null || f_exit_success_with_msg "couldn't find ${cmd}, skipping"
  done
}

f_check_cmds

if [[ $STAGED_GO_FILES != "" ]]; then
  echo "[pre-commit] fmt'ing staged files..." >&2
  for file in $STAGED_GO_FILES; do
    if [[ $file =~ vendor/ ]] || [[ $file =~ client/lcd/statik/ ]] || [[ $file =~ tests/mocks/ ]]; then
      continue
    fi

    gofmt -w -s $file
    misspell -w $file
    goimports -w -local github.com/cosmos/cosmos-sdk $file
    git add $file

  done
fi
