package module

import (
	"embed"

	"google.golang.org/protobuf/proto"
)

// Register registers a module with the dependency injection system.
//
// configType should be a protobuf type with the cosmos.app.v1alpha1.module option.
// It is the type that should be used in the declarative app config as described
// by cosmos.app.v1alpha.Config.
//
// pinnedProtoImageFS is an embedded protobuf image generated by buf build.
// The protobuf image should be named proto_image.bin.gz and to keep the image
// small, it only needs to contain the protobuf files used in the module
// (referenced in the cosmos.app.v1alpha1.ModuleDescriptor.use_package field).
// The buf build --path and --exclude-imports options can be used to restrict
// this. Ex: "buf build --path ../proto/foo/bar --exclude-imports -o proto_image.bin.bz".
//
// options are the module options where dependency injection providers are actually
// registered.
func Register(configType proto.Message, pinnedProtoImageFS embed.FS, options ...Option) {
	panic("TODO")
}
