#!/bin/sh

echo Chain 2 from zipped binary
echo Args: $@
# note that we just have a url (follow the ref), not a full link
echo 'ERROR: UPGRADE "chain3" NEEDED at height: 936: ref_to_chain3-zip_dir.json module=main'

# this update info doesn't contain binaries, instead it is a reference for further download instructions.
cat > "$3" <<EOL
{
	"name": "chain3",
	"height": 936,
	"info": "https://github.com/cosmos/cosmos-sdk/raw/main/tools/cosmovisor/testdata/repo/ref_to_chain3-zip_dir.json?checksum=sha256:6758973f7404f6d34381029931b85826fc7a6315584ede03bad4c19e9b787f6c"
}
EOL

sleep 1
echo 'Do not print'
