FROM bufbuild/buf:1.1.0 as BUILDER

FROM golang:alpine

ENV GOLANG_PROTOBUF_VERSION=1.27.1 \
  GOGO_PROTOBUF_VERSION=1.3.2 \
  GRPC_GATEWAY_VERSION=1.14.7


RUN GO111MODULE=on go install github.com/cosmos/cosmos-proto/cmd/protoc-gen-go-pulsar@latest 
RUN GO111MODULE=on go install google.golang.org/protobuf/cmd/protoc-gen-go@v${GOLANG_PROTOBUF_VERSION}
RUN GO111MODULE=on go install github.com/gogo/protobuf/protoc-gen-gogo@v${GOGO_PROTOBUF_VERSION} 
RUN GO111MODULE=on go install github.com/gogo/protobuf/protoc-gen-gogofast@v${GOGO_PROTOBUF_VERSION} 
RUN GO111MODULE=on go install github.com/gogo/protobuf/protoc-gen-gogofaster@v${GOGO_PROTOBUF_VERSION} 
RUN GO111MODULE=on go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v${GRPC_GATEWAY_VERSION} 
RUN GO111MODULE=on go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@v${GRPC_GATEWAY_VERSION} 

RUN apk add --no-cache \
  nodejs \
  npm

RUN npm install -g swagger-combine

COPY --from=BUILDER /usr/local/bin /usr/local/bin
