package errors

const testCodespace = "sdk"

var (
	errTxDecode                = Register(testCodespace, 2, "tx parse error")
	errInvalidSequence         = Register(testCodespace, 3, "invalid sequence")
	errUnauthorized            = Register(testCodespace, 4, "unauthorized")
	errInsufficientFunds       = Register(testCodespace, 5, "insufficient funds")
	errUnknownRequest          = Register(testCodespace, 6, "unknown request")
	errInvalidAddress          = Register(testCodespace, 7, "invalid address")
	errInvalidPubKey           = Register(testCodespace, 8, "invalid pubkey")
	errUnknownAddress          = Register(testCodespace, 9, "unknown address")
	errInvalidCoins            = Register(testCodespace, 10, "invalid coins")
	errOutOfGas                = Register(testCodespace, 11, "out of gas")
	errInsufficientFee         = Register(testCodespace, 13, "insufficient fee")
	errTooManySignatures       = Register(testCodespace, 14, "maximum number of signatures exceeded")
	ErrNoSignatures            = Register(testCodespace, 15, "no signatures supplied")
	ErrJSONMarshal             = Register(testCodespace, 16, "failed to marshal JSON bytes")
	ErrJSONUnmarshal           = Register(testCodespace, 17, "failed to unmarshal JSON bytes")
	ErrInvalidRequest          = Register(testCodespace, 18, "invalid request")
	ErrMempoolIsFull           = Register(testCodespace, 20, "mempool is full")
	ErrTxTooLarge              = Register(testCodespace, 21, "tx too large")
	ErrKeyNotFound             = Register(testCodespace, 22, "key not found")
	ErrorInvalidSigner         = Register(testCodespace, 24, "tx intended signer does not match the given signer")
	ErrInvalidChainID          = Register(testCodespace, 28, "invalid chain-id")
	ErrInvalidType             = Register(testCodespace, 29, "invalid type")
	ErrUnknownExtensionOptions = Register(testCodespace, 31, "unknown extension options")
	ErrPackAny                 = Register(testCodespace, 33, "failed packing protobuf message to Any")
	ErrLogic                   = Register(testCodespace, 35, "internal logic error")
	ErrConflict                = Register(testCodespace, 36, "conflict")
	ErrNotSupported            = Register(testCodespace, 37, "feature not supported")
	ErrNotFound                = Register(testCodespace, 38, "not found")
	ErrIO                      = Register(testCodespace, 39, "Internal IO error")
)
