name: Lint
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
  merge_group:
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.23"
          check-latest: true
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.mk
            Makefile
            **/Makefile
            .golangci.yml
      - name: Get rocksdb version
        run: ./.github/scripts/get-rocksdb-version.sh
      - name: Fix permissions for cache
        run: sudo chown $(whoami) /usr/local/lib /usr/local/include
      - name: Restore rocksdb libraries cache
        id: cache-rocksdb
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            /usr/local/lib/librocksdb.*
            /usr/local/include/rocksdb
          key: ${{ runner.os }}-rocksdb-${{ env.ROCKSDB_VERSION }}-amd64
      - name: Install rocksdb deps
        run: ./.github/scripts/install-rocksdb-deps.sh
      - name: Install rocksdb
        if: steps.cache-rocksdb.outputs.cache-hit != 'true'
        run: ./.github/scripts/install-rocksdb.sh
      - name: run linting (long)
        if: env.GIT_DIFF
        id: lint_long
        run: |
          make lint
        env:
          ROCKSDB: 1
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        if: steps.lint_long.outcome == 'skipped'
        with:
          PATTERNS: |
            **/*.go
            *.go
            !store/**
      - name: run linting (short)
        if: steps.lint_long.outcome == 'skipped' && env.GIT_DIFF
        run: |
          make lint
        env:
          GIT_DIFF: ${{ env.GIT_DIFF }}
          LINT_DIFF: 1
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        if: steps.lint_long.outcome == 'skipped'
        with:
          PATTERNS: |
            store/**
      - name: run linting (short)
        if: steps.lint_long.outcome == 'skipped' && env.GIT_DIFF
        run: |
          make lint
        env:
          GIT_DIFF: ${{ env.GIT_DIFF }}
          LINT_DIFF: 1
          ROCKSDB: 1
